// Code generated by entc, DO NOT EDIT.

package datadictionaryvalue

const (
	// Label holds the string label denoting the datadictionaryvalue type in the database.
	Label = "data_dictionary_value"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the datadictionaryvalue in the database.
	Table = "data_dictionary_values"
)

// Columns holds all SQL columns for datadictionaryvalue fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
