// Code generated by entc, DO NOT EDIT.

package messageread

const (
	// Label holds the string label denoting the messageread type in the database.
	Label = "message_read"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the messageread in the database.
	Table = "message_reads"
)

// Columns holds all SQL columns for messageread fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
