// Code generated by entc, DO NOT EDIT.

package categorybanner

const (
	// Label holds the string label denoting the categorybanner type in the database.
	Label = "category_banner"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the categorybanner in the database.
	Table = "category_banners"
)

// Columns holds all SQL columns for categorybanner fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
