// Code generated by entc, DO NOT EDIT.

package popularsearch

const (
	// Label holds the string label denoting the popularsearch type in the database.
	Label = "popular_search"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the popularsearch in the database.
	Table = "popular_searches"
)

// Columns holds all SQL columns for popularsearch fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
