// Code generated by entc, DO NOT EDIT.

package annex

const (
	// Label holds the string label denoting the annex type in the database.
	Label = "annex"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the annex in the database.
	Table = "annexes"
)

// Columns holds all SQL columns for annex fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
