// Code generated by entc, DO NOT EDIT.

package productspecs

const (
	// Label holds the string label denoting the productspecs type in the database.
	Label = "product_specs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the productspecs in the database.
	Table = "product_specs"
)

// Columns holds all SQL columns for productspecs fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
