// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/aftermarket"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Aftermarket is the model entity for the Aftermarket schema.
type Aftermarket struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Aftermarket) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case aftermarket.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Aftermarket", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Aftermarket fields.
func (a *Aftermarket) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aftermarket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Aftermarket.
// Note that you need to call Aftermarket.Unwrap() before calling this method if this Aftermarket
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Aftermarket) Update() *AftermarketUpdateOne {
	return (&AftermarketClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Aftermarket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Aftermarket) Unwrap() *Aftermarket {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Aftermarket is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Aftermarket) String() string {
	var builder strings.Builder
	builder.WriteString("Aftermarket(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Aftermarkets is a parsable slice of Aftermarket.
type Aftermarkets []*Aftermarket

func (a Aftermarkets) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
