// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/annex"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Annex is the model entity for the Annex schema.
type Annex struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Annex) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case annex.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Annex", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Annex fields.
func (a *Annex) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case annex.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Annex.
// Note that you need to call Annex.Unwrap() before calling this method if this Annex
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Annex) Update() *AnnexUpdateOne {
	return (&AnnexClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Annex entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Annex) Unwrap() *Annex {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Annex is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Annex) String() string {
	var builder strings.Builder
	builder.WriteString("Annex(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Annexes is a parsable slice of Annex.
type Annexes []*Annex

func (a Annexes) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
