// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/captcha"
	"ice-mall/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CaptchaUpdate is the builder for updating Captcha entities.
type CaptchaUpdate struct {
	config
	hooks    []Hook
	mutation *CaptchaMutation
}

// Where appends a list predicates to the CaptchaUpdate builder.
func (cu *CaptchaUpdate) Where(ps ...predicate.Captcha) *CaptchaUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCreatedAt sets the "createdAt" field.
func (cu *CaptchaUpdate) SetCreatedAt(t time.Time) *CaptchaUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (cu *CaptchaUpdate) SetNillableCreatedAt(t *time.Time) *CaptchaUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updatedAt" field.
func (cu *CaptchaUpdate) SetUpdatedAt(t time.Time) *CaptchaUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetDeletedAt sets the "deletedAt" field.
func (cu *CaptchaUpdate) SetDeletedAt(t time.Time) *CaptchaUpdate {
	cu.mutation.SetDeletedAt(t)
	return cu
}

// SetNillableDeletedAt sets the "deletedAt" field if the given value is not nil.
func (cu *CaptchaUpdate) SetNillableDeletedAt(t *time.Time) *CaptchaUpdate {
	if t != nil {
		cu.SetDeletedAt(*t)
	}
	return cu
}

// ClearDeletedAt clears the value of the "deletedAt" field.
func (cu *CaptchaUpdate) ClearDeletedAt() *CaptchaUpdate {
	cu.mutation.ClearDeletedAt()
	return cu
}

// SetType sets the "type" field.
func (cu *CaptchaUpdate) SetType(c captcha.Type) *CaptchaUpdate {
	cu.mutation.SetType(c)
	return cu
}

// SetPhone sets the "phone" field.
func (cu *CaptchaUpdate) SetPhone(s string) *CaptchaUpdate {
	cu.mutation.SetPhone(s)
	return cu
}

// SetCode sets the "code" field.
func (cu *CaptchaUpdate) SetCode(s string) *CaptchaUpdate {
	cu.mutation.SetCode(s)
	return cu
}

// Mutation returns the CaptchaMutation object of the builder.
func (cu *CaptchaUpdate) Mutation() *CaptchaMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CaptchaUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	cu.defaults()
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CaptchaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CaptchaUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CaptchaUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CaptchaUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CaptchaUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := captcha.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CaptchaUpdate) check() error {
	if v, ok := cu.mutation.GetType(); ok {
		if err := captcha.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Captcha.type": %w`, err)}
		}
	}
	return nil
}

func (cu *CaptchaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   captcha.Table,
			Columns: captcha.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: captcha.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldCreatedAt,
		})
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldUpdatedAt,
		})
	}
	if value, ok := cu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldDeletedAt,
		})
	}
	if cu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: captcha.FieldDeletedAt,
		})
	}
	if value, ok := cu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: captcha.FieldType,
		})
	}
	if value, ok := cu.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: captcha.FieldPhone,
		})
	}
	if value, ok := cu.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: captcha.FieldCode,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{captcha.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CaptchaUpdateOne is the builder for updating a single Captcha entity.
type CaptchaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CaptchaMutation
}

// SetCreatedAt sets the "createdAt" field.
func (cuo *CaptchaUpdateOne) SetCreatedAt(t time.Time) *CaptchaUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (cuo *CaptchaUpdateOne) SetNillableCreatedAt(t *time.Time) *CaptchaUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updatedAt" field.
func (cuo *CaptchaUpdateOne) SetUpdatedAt(t time.Time) *CaptchaUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetDeletedAt sets the "deletedAt" field.
func (cuo *CaptchaUpdateOne) SetDeletedAt(t time.Time) *CaptchaUpdateOne {
	cuo.mutation.SetDeletedAt(t)
	return cuo
}

// SetNillableDeletedAt sets the "deletedAt" field if the given value is not nil.
func (cuo *CaptchaUpdateOne) SetNillableDeletedAt(t *time.Time) *CaptchaUpdateOne {
	if t != nil {
		cuo.SetDeletedAt(*t)
	}
	return cuo
}

// ClearDeletedAt clears the value of the "deletedAt" field.
func (cuo *CaptchaUpdateOne) ClearDeletedAt() *CaptchaUpdateOne {
	cuo.mutation.ClearDeletedAt()
	return cuo
}

// SetType sets the "type" field.
func (cuo *CaptchaUpdateOne) SetType(c captcha.Type) *CaptchaUpdateOne {
	cuo.mutation.SetType(c)
	return cuo
}

// SetPhone sets the "phone" field.
func (cuo *CaptchaUpdateOne) SetPhone(s string) *CaptchaUpdateOne {
	cuo.mutation.SetPhone(s)
	return cuo
}

// SetCode sets the "code" field.
func (cuo *CaptchaUpdateOne) SetCode(s string) *CaptchaUpdateOne {
	cuo.mutation.SetCode(s)
	return cuo
}

// Mutation returns the CaptchaMutation object of the builder.
func (cuo *CaptchaUpdateOne) Mutation() *CaptchaMutation {
	return cuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CaptchaUpdateOne) Select(field string, fields ...string) *CaptchaUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Captcha entity.
func (cuo *CaptchaUpdateOne) Save(ctx context.Context) (*Captcha, error) {
	var (
		err  error
		node *Captcha
	)
	cuo.defaults()
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CaptchaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CaptchaUpdateOne) SaveX(ctx context.Context) *Captcha {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CaptchaUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CaptchaUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CaptchaUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := captcha.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CaptchaUpdateOne) check() error {
	if v, ok := cuo.mutation.GetType(); ok {
		if err := captcha.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Captcha.type": %w`, err)}
		}
	}
	return nil
}

func (cuo *CaptchaUpdateOne) sqlSave(ctx context.Context) (_node *Captcha, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   captcha.Table,
			Columns: captcha.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: captcha.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Captcha.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, captcha.FieldID)
		for _, f := range fields {
			if !captcha.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != captcha.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldCreatedAt,
		})
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldUpdatedAt,
		})
	}
	if value, ok := cuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: captcha.FieldDeletedAt,
		})
	}
	if cuo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: captcha.FieldDeletedAt,
		})
	}
	if value, ok := cuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: captcha.FieldType,
		})
	}
	if value, ok := cuo.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: captcha.FieldPhone,
		})
	}
	if value, ok := cuo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: captcha.FieldCode,
		})
	}
	_node = &Captcha{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{captcha.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
