// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/datadictionaryvalue"
	"ice-mall/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataDictionaryValueDelete is the builder for deleting a DataDictionaryValue entity.
type DataDictionaryValueDelete struct {
	config
	hooks    []Hook
	mutation *DataDictionaryValueMutation
}

// Where appends a list predicates to the DataDictionaryValueDelete builder.
func (ddvd *DataDictionaryValueDelete) Where(ps ...predicate.DataDictionaryValue) *DataDictionaryValueDelete {
	ddvd.mutation.Where(ps...)
	return ddvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ddvd *DataDictionaryValueDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ddvd.hooks) == 0 {
		affected, err = ddvd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataDictionaryValueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ddvd.mutation = mutation
			affected, err = ddvd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ddvd.hooks) - 1; i >= 0; i-- {
			if ddvd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ddvd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ddvd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddvd *DataDictionaryValueDelete) ExecX(ctx context.Context) int {
	n, err := ddvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ddvd *DataDictionaryValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: datadictionaryvalue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datadictionaryvalue.FieldID,
			},
		},
	}
	if ps := ddvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ddvd.driver, _spec)
}

// DataDictionaryValueDeleteOne is the builder for deleting a single DataDictionaryValue entity.
type DataDictionaryValueDeleteOne struct {
	ddvd *DataDictionaryValueDelete
}

// Exec executes the deletion query.
func (ddvdo *DataDictionaryValueDeleteOne) Exec(ctx context.Context) error {
	n, err := ddvdo.ddvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{datadictionaryvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddvdo *DataDictionaryValueDeleteOne) ExecX(ctx context.Context) {
	ddvdo.ddvd.ExecX(ctx)
}
