// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/datadictionarykey"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataDictionaryKeyCreate is the builder for creating a DataDictionaryKey entity.
type DataDictionaryKeyCreate struct {
	config
	mutation *DataDictionaryKeyMutation
	hooks    []Hook
}

// Mutation returns the DataDictionaryKeyMutation object of the builder.
func (ddkc *DataDictionaryKeyCreate) Mutation() *DataDictionaryKeyMutation {
	return ddkc.mutation
}

// Save creates the DataDictionaryKey in the database.
func (ddkc *DataDictionaryKeyCreate) Save(ctx context.Context) (*DataDictionaryKey, error) {
	var (
		err  error
		node *DataDictionaryKey
	)
	if len(ddkc.hooks) == 0 {
		if err = ddkc.check(); err != nil {
			return nil, err
		}
		node, err = ddkc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataDictionaryKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ddkc.check(); err != nil {
				return nil, err
			}
			ddkc.mutation = mutation
			if node, err = ddkc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ddkc.hooks) - 1; i >= 0; i-- {
			if ddkc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ddkc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ddkc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ddkc *DataDictionaryKeyCreate) SaveX(ctx context.Context) *DataDictionaryKey {
	v, err := ddkc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ddkc *DataDictionaryKeyCreate) Exec(ctx context.Context) error {
	_, err := ddkc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddkc *DataDictionaryKeyCreate) ExecX(ctx context.Context) {
	if err := ddkc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ddkc *DataDictionaryKeyCreate) check() error {
	return nil
}

func (ddkc *DataDictionaryKeyCreate) sqlSave(ctx context.Context) (*DataDictionaryKey, error) {
	_node, _spec := ddkc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ddkc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ddkc *DataDictionaryKeyCreate) createSpec() (*DataDictionaryKey, *sqlgraph.CreateSpec) {
	var (
		_node = &DataDictionaryKey{config: ddkc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: datadictionarykey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datadictionarykey.FieldID,
			},
		}
	)
	return _node, _spec
}

// DataDictionaryKeyCreateBulk is the builder for creating many DataDictionaryKey entities in bulk.
type DataDictionaryKeyCreateBulk struct {
	config
	builders []*DataDictionaryKeyCreate
}

// Save creates the DataDictionaryKey entities in the database.
func (ddkcb *DataDictionaryKeyCreateBulk) Save(ctx context.Context) ([]*DataDictionaryKey, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ddkcb.builders))
	nodes := make([]*DataDictionaryKey, len(ddkcb.builders))
	mutators := make([]Mutator, len(ddkcb.builders))
	for i := range ddkcb.builders {
		func(i int, root context.Context) {
			builder := ddkcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DataDictionaryKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ddkcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ddkcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ddkcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ddkcb *DataDictionaryKeyCreateBulk) SaveX(ctx context.Context) []*DataDictionaryKey {
	v, err := ddkcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ddkcb *DataDictionaryKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := ddkcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddkcb *DataDictionaryKeyCreateBulk) ExecX(ctx context.Context) {
	if err := ddkcb.Exec(ctx); err != nil {
		panic(err)
	}
}
