// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/datadictionarykey"
	"ice-mall/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataDictionaryKeyDelete is the builder for deleting a DataDictionaryKey entity.
type DataDictionaryKeyDelete struct {
	config
	hooks    []Hook
	mutation *DataDictionaryKeyMutation
}

// Where appends a list predicates to the DataDictionaryKeyDelete builder.
func (ddkd *DataDictionaryKeyDelete) Where(ps ...predicate.DataDictionaryKey) *DataDictionaryKeyDelete {
	ddkd.mutation.Where(ps...)
	return ddkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ddkd *DataDictionaryKeyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ddkd.hooks) == 0 {
		affected, err = ddkd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataDictionaryKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ddkd.mutation = mutation
			affected, err = ddkd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ddkd.hooks) - 1; i >= 0; i-- {
			if ddkd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ddkd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ddkd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddkd *DataDictionaryKeyDelete) ExecX(ctx context.Context) int {
	n, err := ddkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ddkd *DataDictionaryKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: datadictionarykey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datadictionarykey.FieldID,
			},
		},
	}
	if ps := ddkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ddkd.driver, _spec)
}

// DataDictionaryKeyDeleteOne is the builder for deleting a single DataDictionaryKey entity.
type DataDictionaryKeyDeleteOne struct {
	ddkd *DataDictionaryKeyDelete
}

// Exec executes the deletion query.
func (ddkdo *DataDictionaryKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := ddkdo.ddkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{datadictionarykey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddkdo *DataDictionaryKeyDeleteOne) ExecX(ctx context.Context) {
	ddkdo.ddkd.ExecX(ctx)
}
