// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/datadictionaryvalue"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataDictionaryValueCreate is the builder for creating a DataDictionaryValue entity.
type DataDictionaryValueCreate struct {
	config
	mutation *DataDictionaryValueMutation
	hooks    []Hook
}

// Mutation returns the DataDictionaryValueMutation object of the builder.
func (ddvc *DataDictionaryValueCreate) Mutation() *DataDictionaryValueMutation {
	return ddvc.mutation
}

// Save creates the DataDictionaryValue in the database.
func (ddvc *DataDictionaryValueCreate) Save(ctx context.Context) (*DataDictionaryValue, error) {
	var (
		err  error
		node *DataDictionaryValue
	)
	if len(ddvc.hooks) == 0 {
		if err = ddvc.check(); err != nil {
			return nil, err
		}
		node, err = ddvc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataDictionaryValueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ddvc.check(); err != nil {
				return nil, err
			}
			ddvc.mutation = mutation
			if node, err = ddvc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ddvc.hooks) - 1; i >= 0; i-- {
			if ddvc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ddvc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ddvc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ddvc *DataDictionaryValueCreate) SaveX(ctx context.Context) *DataDictionaryValue {
	v, err := ddvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ddvc *DataDictionaryValueCreate) Exec(ctx context.Context) error {
	_, err := ddvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddvc *DataDictionaryValueCreate) ExecX(ctx context.Context) {
	if err := ddvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ddvc *DataDictionaryValueCreate) check() error {
	return nil
}

func (ddvc *DataDictionaryValueCreate) sqlSave(ctx context.Context) (*DataDictionaryValue, error) {
	_node, _spec := ddvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ddvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ddvc *DataDictionaryValueCreate) createSpec() (*DataDictionaryValue, *sqlgraph.CreateSpec) {
	var (
		_node = &DataDictionaryValue{config: ddvc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: datadictionaryvalue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datadictionaryvalue.FieldID,
			},
		}
	)
	return _node, _spec
}

// DataDictionaryValueCreateBulk is the builder for creating many DataDictionaryValue entities in bulk.
type DataDictionaryValueCreateBulk struct {
	config
	builders []*DataDictionaryValueCreate
}

// Save creates the DataDictionaryValue entities in the database.
func (ddvcb *DataDictionaryValueCreateBulk) Save(ctx context.Context) ([]*DataDictionaryValue, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ddvcb.builders))
	nodes := make([]*DataDictionaryValue, len(ddvcb.builders))
	mutators := make([]Mutator, len(ddvcb.builders))
	for i := range ddvcb.builders {
		func(i int, root context.Context) {
			builder := ddvcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DataDictionaryValueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ddvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ddvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ddvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ddvcb *DataDictionaryValueCreateBulk) SaveX(ctx context.Context) []*DataDictionaryValue {
	v, err := ddvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ddvcb *DataDictionaryValueCreateBulk) Exec(ctx context.Context) error {
	_, err := ddvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ddvcb *DataDictionaryValueCreateBulk) ExecX(ctx context.Context) {
	if err := ddvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
