// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/datadictionaryvalue"
	"ice-mall/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataDictionaryValueQuery is the builder for querying DataDictionaryValue entities.
type DataDictionaryValueQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DataDictionaryValue
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DataDictionaryValueQuery builder.
func (ddvq *DataDictionaryValueQuery) Where(ps ...predicate.DataDictionaryValue) *DataDictionaryValueQuery {
	ddvq.predicates = append(ddvq.predicates, ps...)
	return ddvq
}

// Limit adds a limit step to the query.
func (ddvq *DataDictionaryValueQuery) Limit(limit int) *DataDictionaryValueQuery {
	ddvq.limit = &limit
	return ddvq
}

// Offset adds an offset step to the query.
func (ddvq *DataDictionaryValueQuery) Offset(offset int) *DataDictionaryValueQuery {
	ddvq.offset = &offset
	return ddvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddvq *DataDictionaryValueQuery) Unique(unique bool) *DataDictionaryValueQuery {
	ddvq.unique = &unique
	return ddvq
}

// Order adds an order step to the query.
func (ddvq *DataDictionaryValueQuery) Order(o ...OrderFunc) *DataDictionaryValueQuery {
	ddvq.order = append(ddvq.order, o...)
	return ddvq
}

// First returns the first DataDictionaryValue entity from the query.
// Returns a *NotFoundError when no DataDictionaryValue was found.
func (ddvq *DataDictionaryValueQuery) First(ctx context.Context) (*DataDictionaryValue, error) {
	nodes, err := ddvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{datadictionaryvalue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) FirstX(ctx context.Context) *DataDictionaryValue {
	node, err := ddvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DataDictionaryValue ID from the query.
// Returns a *NotFoundError when no DataDictionaryValue ID was found.
func (ddvq *DataDictionaryValueQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{datadictionaryvalue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) FirstIDX(ctx context.Context) int {
	id, err := ddvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DataDictionaryValue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DataDictionaryValue entity is found.
// Returns a *NotFoundError when no DataDictionaryValue entities are found.
func (ddvq *DataDictionaryValueQuery) Only(ctx context.Context) (*DataDictionaryValue, error) {
	nodes, err := ddvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{datadictionaryvalue.Label}
	default:
		return nil, &NotSingularError{datadictionaryvalue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) OnlyX(ctx context.Context) *DataDictionaryValue {
	node, err := ddvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DataDictionaryValue ID in the query.
// Returns a *NotSingularError when more than one DataDictionaryValue ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddvq *DataDictionaryValueQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = &NotSingularError{datadictionaryvalue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DataDictionaryValues.
func (ddvq *DataDictionaryValueQuery) All(ctx context.Context) ([]*DataDictionaryValue, error) {
	if err := ddvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ddvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) AllX(ctx context.Context) []*DataDictionaryValue {
	nodes, err := ddvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DataDictionaryValue IDs.
func (ddvq *DataDictionaryValueQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ddvq.Select(datadictionaryvalue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) IDsX(ctx context.Context) []int {
	ids, err := ddvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddvq *DataDictionaryValueQuery) Count(ctx context.Context) (int, error) {
	if err := ddvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ddvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) CountX(ctx context.Context) int {
	count, err := ddvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddvq *DataDictionaryValueQuery) Exist(ctx context.Context) (bool, error) {
	if err := ddvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ddvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ddvq *DataDictionaryValueQuery) ExistX(ctx context.Context) bool {
	exist, err := ddvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DataDictionaryValueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddvq *DataDictionaryValueQuery) Clone() *DataDictionaryValueQuery {
	if ddvq == nil {
		return nil
	}
	return &DataDictionaryValueQuery{
		config:     ddvq.config,
		limit:      ddvq.limit,
		offset:     ddvq.offset,
		order:      append([]OrderFunc{}, ddvq.order...),
		predicates: append([]predicate.DataDictionaryValue{}, ddvq.predicates...),
		// clone intermediate query.
		sql:    ddvq.sql.Clone(),
		path:   ddvq.path,
		unique: ddvq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ddvq *DataDictionaryValueQuery) GroupBy(field string, fields ...string) *DataDictionaryValueGroupBy {
	group := &DataDictionaryValueGroupBy{config: ddvq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ddvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ddvq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ddvq *DataDictionaryValueQuery) Select(fields ...string) *DataDictionaryValueSelect {
	ddvq.fields = append(ddvq.fields, fields...)
	return &DataDictionaryValueSelect{DataDictionaryValueQuery: ddvq}
}

func (ddvq *DataDictionaryValueQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ddvq.fields {
		if !datadictionaryvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddvq.path != nil {
		prev, err := ddvq.path(ctx)
		if err != nil {
			return err
		}
		ddvq.sql = prev
	}
	return nil
}

func (ddvq *DataDictionaryValueQuery) sqlAll(ctx context.Context) ([]*DataDictionaryValue, error) {
	var (
		nodes = []*DataDictionaryValue{}
		_spec = ddvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &DataDictionaryValue{config: ddvq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ddvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ddvq *DataDictionaryValueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddvq.querySpec()
	_spec.Node.Columns = ddvq.fields
	if len(ddvq.fields) > 0 {
		_spec.Unique = ddvq.unique != nil && *ddvq.unique
	}
	return sqlgraph.CountNodes(ctx, ddvq.driver, _spec)
}

func (ddvq *DataDictionaryValueQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ddvq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ddvq *DataDictionaryValueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   datadictionaryvalue.Table,
			Columns: datadictionaryvalue.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datadictionaryvalue.FieldID,
			},
		},
		From:   ddvq.sql,
		Unique: true,
	}
	if unique := ddvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ddvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datadictionaryvalue.FieldID)
		for i := range fields {
			if fields[i] != datadictionaryvalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddvq *DataDictionaryValueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddvq.driver.Dialect())
	t1 := builder.Table(datadictionaryvalue.Table)
	columns := ddvq.fields
	if len(columns) == 0 {
		columns = datadictionaryvalue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddvq.sql != nil {
		selector = ddvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddvq.unique != nil && *ddvq.unique {
		selector.Distinct()
	}
	for _, p := range ddvq.predicates {
		p(selector)
	}
	for _, p := range ddvq.order {
		p(selector)
	}
	if offset := ddvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DataDictionaryValueGroupBy is the group-by builder for DataDictionaryValue entities.
type DataDictionaryValueGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddvgb *DataDictionaryValueGroupBy) Aggregate(fns ...AggregateFunc) *DataDictionaryValueGroupBy {
	ddvgb.fns = append(ddvgb.fns, fns...)
	return ddvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ddvgb *DataDictionaryValueGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ddvgb.path(ctx)
	if err != nil {
		return err
	}
	ddvgb.sql = query
	return ddvgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ddvgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ddvgb.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ddvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) StringsX(ctx context.Context) []string {
	v, err := ddvgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ddvgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) StringX(ctx context.Context) string {
	v, err := ddvgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ddvgb.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ddvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) IntsX(ctx context.Context) []int {
	v, err := ddvgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ddvgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) IntX(ctx context.Context) int {
	v, err := ddvgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ddvgb.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ddvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ddvgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ddvgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ddvgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ddvgb.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ddvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ddvgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ddvgb *DataDictionaryValueGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ddvgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ddvgb *DataDictionaryValueGroupBy) BoolX(ctx context.Context) bool {
	v, err := ddvgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ddvgb *DataDictionaryValueGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ddvgb.fields {
		if !datadictionaryvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ddvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ddvgb *DataDictionaryValueGroupBy) sqlQuery() *sql.Selector {
	selector := ddvgb.sql.Select()
	aggregation := make([]string, 0, len(ddvgb.fns))
	for _, fn := range ddvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ddvgb.fields)+len(ddvgb.fns))
		for _, f := range ddvgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ddvgb.fields...)...)
}

// DataDictionaryValueSelect is the builder for selecting fields of DataDictionaryValue entities.
type DataDictionaryValueSelect struct {
	*DataDictionaryValueQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ddvs *DataDictionaryValueSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ddvs.prepareQuery(ctx); err != nil {
		return err
	}
	ddvs.sql = ddvs.DataDictionaryValueQuery.sqlQuery(ctx)
	return ddvs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ddvs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ddvs.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ddvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) StringsX(ctx context.Context) []string {
	v, err := ddvs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ddvs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) StringX(ctx context.Context) string {
	v, err := ddvs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ddvs.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ddvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) IntsX(ctx context.Context) []int {
	v, err := ddvs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ddvs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) IntX(ctx context.Context) int {
	v, err := ddvs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ddvs.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ddvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ddvs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ddvs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) Float64X(ctx context.Context) float64 {
	v, err := ddvs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ddvs.fields) > 1 {
		return nil, errors.New("ent: DataDictionaryValueSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ddvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) BoolsX(ctx context.Context) []bool {
	v, err := ddvs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ddvs *DataDictionaryValueSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ddvs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{datadictionaryvalue.Label}
	default:
		err = fmt.Errorf("ent: DataDictionaryValueSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ddvs *DataDictionaryValueSelect) BoolX(ctx context.Context) bool {
	v, err := ddvs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ddvs *DataDictionaryValueSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ddvs.sql.Query()
	if err := ddvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
