// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/homebanner"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HomeBannerCreate is the builder for creating a HomeBanner entity.
type HomeBannerCreate struct {
	config
	mutation *HomeBannerMutation
	hooks    []Hook
}

// Mutation returns the HomeBannerMutation object of the builder.
func (hbc *HomeBannerCreate) Mutation() *HomeBannerMutation {
	return hbc.mutation
}

// Save creates the HomeBanner in the database.
func (hbc *HomeBannerCreate) Save(ctx context.Context) (*HomeBanner, error) {
	var (
		err  error
		node *HomeBanner
	)
	if len(hbc.hooks) == 0 {
		if err = hbc.check(); err != nil {
			return nil, err
		}
		node, err = hbc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HomeBannerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hbc.check(); err != nil {
				return nil, err
			}
			hbc.mutation = mutation
			if node, err = hbc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hbc.hooks) - 1; i >= 0; i-- {
			if hbc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hbc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hbc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hbc *HomeBannerCreate) SaveX(ctx context.Context) *HomeBanner {
	v, err := hbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hbc *HomeBannerCreate) Exec(ctx context.Context) error {
	_, err := hbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbc *HomeBannerCreate) ExecX(ctx context.Context) {
	if err := hbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hbc *HomeBannerCreate) check() error {
	return nil
}

func (hbc *HomeBannerCreate) sqlSave(ctx context.Context) (*HomeBanner, error) {
	_node, _spec := hbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hbc *HomeBannerCreate) createSpec() (*HomeBanner, *sqlgraph.CreateSpec) {
	var (
		_node = &HomeBanner{config: hbc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: homebanner.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: homebanner.FieldID,
			},
		}
	)
	return _node, _spec
}

// HomeBannerCreateBulk is the builder for creating many HomeBanner entities in bulk.
type HomeBannerCreateBulk struct {
	config
	builders []*HomeBannerCreate
}

// Save creates the HomeBanner entities in the database.
func (hbcb *HomeBannerCreateBulk) Save(ctx context.Context) ([]*HomeBanner, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hbcb.builders))
	nodes := make([]*HomeBanner, len(hbcb.builders))
	mutators := make([]Mutator, len(hbcb.builders))
	for i := range hbcb.builders {
		func(i int, root context.Context) {
			builder := hbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HomeBannerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hbcb *HomeBannerCreateBulk) SaveX(ctx context.Context) []*HomeBanner {
	v, err := hbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hbcb *HomeBannerCreateBulk) Exec(ctx context.Context) error {
	_, err := hbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbcb *HomeBannerCreateBulk) ExecX(ctx context.Context) {
	if err := hbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
