// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/homebanner"
	"ice-mall/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HomeBannerUpdate is the builder for updating HomeBanner entities.
type HomeBannerUpdate struct {
	config
	hooks    []Hook
	mutation *HomeBannerMutation
}

// Where appends a list predicates to the HomeBannerUpdate builder.
func (hbu *HomeBannerUpdate) Where(ps ...predicate.HomeBanner) *HomeBannerUpdate {
	hbu.mutation.Where(ps...)
	return hbu
}

// Mutation returns the HomeBannerMutation object of the builder.
func (hbu *HomeBannerUpdate) Mutation() *HomeBannerMutation {
	return hbu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hbu *HomeBannerUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(hbu.hooks) == 0 {
		affected, err = hbu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HomeBannerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hbu.mutation = mutation
			affected, err = hbu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hbu.hooks) - 1; i >= 0; i-- {
			if hbu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hbu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hbu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (hbu *HomeBannerUpdate) SaveX(ctx context.Context) int {
	affected, err := hbu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hbu *HomeBannerUpdate) Exec(ctx context.Context) error {
	_, err := hbu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbu *HomeBannerUpdate) ExecX(ctx context.Context) {
	if err := hbu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hbu *HomeBannerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   homebanner.Table,
			Columns: homebanner.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: homebanner.FieldID,
			},
		},
	}
	if ps := hbu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hbu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{homebanner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// HomeBannerUpdateOne is the builder for updating a single HomeBanner entity.
type HomeBannerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HomeBannerMutation
}

// Mutation returns the HomeBannerMutation object of the builder.
func (hbuo *HomeBannerUpdateOne) Mutation() *HomeBannerMutation {
	return hbuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (hbuo *HomeBannerUpdateOne) Select(field string, fields ...string) *HomeBannerUpdateOne {
	hbuo.fields = append([]string{field}, fields...)
	return hbuo
}

// Save executes the query and returns the updated HomeBanner entity.
func (hbuo *HomeBannerUpdateOne) Save(ctx context.Context) (*HomeBanner, error) {
	var (
		err  error
		node *HomeBanner
	)
	if len(hbuo.hooks) == 0 {
		node, err = hbuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HomeBannerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hbuo.mutation = mutation
			node, err = hbuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(hbuo.hooks) - 1; i >= 0; i-- {
			if hbuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hbuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hbuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (hbuo *HomeBannerUpdateOne) SaveX(ctx context.Context) *HomeBanner {
	node, err := hbuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (hbuo *HomeBannerUpdateOne) Exec(ctx context.Context) error {
	_, err := hbuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbuo *HomeBannerUpdateOne) ExecX(ctx context.Context) {
	if err := hbuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hbuo *HomeBannerUpdateOne) sqlSave(ctx context.Context) (_node *HomeBanner, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   homebanner.Table,
			Columns: homebanner.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: homebanner.FieldID,
			},
		},
	}
	id, ok := hbuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HomeBanner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := hbuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, homebanner.FieldID)
		for _, f := range fields {
			if !homebanner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != homebanner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := hbuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &HomeBanner{config: hbuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, hbuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{homebanner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
