// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/messageread"
	"ice-mall/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageReadDelete is the builder for deleting a MessageRead entity.
type MessageReadDelete struct {
	config
	hooks    []Hook
	mutation *MessageReadMutation
}

// Where appends a list predicates to the MessageReadDelete builder.
func (mrd *MessageReadDelete) Where(ps ...predicate.MessageRead) *MessageReadDelete {
	mrd.mutation.Where(ps...)
	return mrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mrd *MessageReadDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mrd.hooks) == 0 {
		affected, err = mrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageReadMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mrd.mutation = mutation
			affected, err = mrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mrd.hooks) - 1; i >= 0; i-- {
			if mrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrd *MessageReadDelete) ExecX(ctx context.Context) int {
	n, err := mrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mrd *MessageReadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: messageread.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: messageread.FieldID,
			},
		},
	}
	if ps := mrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mrd.driver, _spec)
}

// MessageReadDeleteOne is the builder for deleting a single MessageRead entity.
type MessageReadDeleteOne struct {
	mrd *MessageReadDelete
}

// Exec executes the deletion query.
func (mrdo *MessageReadDeleteOne) Exec(ctx context.Context) error {
	n, err := mrdo.mrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messageread.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mrdo *MessageReadDeleteOne) ExecX(ctx context.Context) {
	mrdo.mrd.ExecX(ctx)
}
