// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/popularsearch"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// PopularSearch is the model entity for the PopularSearch schema.
type PopularSearch struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PopularSearch) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case popularsearch.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PopularSearch", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PopularSearch fields.
func (ps *PopularSearch) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case popularsearch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ps.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this PopularSearch.
// Note that you need to call PopularSearch.Unwrap() before calling this method if this PopularSearch
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *PopularSearch) Update() *PopularSearchUpdateOne {
	return (&PopularSearchClient{config: ps.config}).UpdateOne(ps)
}

// Unwrap unwraps the PopularSearch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *PopularSearch) Unwrap() *PopularSearch {
	tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: PopularSearch is not a transactional entity")
	}
	ps.config.driver = tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *PopularSearch) String() string {
	var builder strings.Builder
	builder.WriteString("PopularSearch(")
	builder.WriteString(fmt.Sprintf("id=%v", ps.ID))
	builder.WriteByte(')')
	return builder.String()
}

// PopularSearches is a parsable slice of PopularSearch.
type PopularSearches []*PopularSearch

func (ps PopularSearches) config(cfg config) {
	for _i := range ps {
		ps[_i].config = cfg
	}
}
