// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productbrowsehistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductBrowseHistoryUpdate is the builder for updating ProductBrowseHistory entities.
type ProductBrowseHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *ProductBrowseHistoryMutation
}

// Where appends a list predicates to the ProductBrowseHistoryUpdate builder.
func (pbhu *ProductBrowseHistoryUpdate) Where(ps ...predicate.ProductBrowseHistory) *ProductBrowseHistoryUpdate {
	pbhu.mutation.Where(ps...)
	return pbhu
}

// Mutation returns the ProductBrowseHistoryMutation object of the builder.
func (pbhu *ProductBrowseHistoryUpdate) Mutation() *ProductBrowseHistoryMutation {
	return pbhu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pbhu *ProductBrowseHistoryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pbhu.hooks) == 0 {
		affected, err = pbhu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductBrowseHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pbhu.mutation = mutation
			affected, err = pbhu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pbhu.hooks) - 1; i >= 0; i-- {
			if pbhu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pbhu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pbhu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pbhu *ProductBrowseHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := pbhu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pbhu *ProductBrowseHistoryUpdate) Exec(ctx context.Context) error {
	_, err := pbhu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pbhu *ProductBrowseHistoryUpdate) ExecX(ctx context.Context) {
	if err := pbhu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pbhu *ProductBrowseHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productbrowsehistory.Table,
			Columns: productbrowsehistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productbrowsehistory.FieldID,
			},
		},
	}
	if ps := pbhu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pbhu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productbrowsehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ProductBrowseHistoryUpdateOne is the builder for updating a single ProductBrowseHistory entity.
type ProductBrowseHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductBrowseHistoryMutation
}

// Mutation returns the ProductBrowseHistoryMutation object of the builder.
func (pbhuo *ProductBrowseHistoryUpdateOne) Mutation() *ProductBrowseHistoryMutation {
	return pbhuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pbhuo *ProductBrowseHistoryUpdateOne) Select(field string, fields ...string) *ProductBrowseHistoryUpdateOne {
	pbhuo.fields = append([]string{field}, fields...)
	return pbhuo
}

// Save executes the query and returns the updated ProductBrowseHistory entity.
func (pbhuo *ProductBrowseHistoryUpdateOne) Save(ctx context.Context) (*ProductBrowseHistory, error) {
	var (
		err  error
		node *ProductBrowseHistory
	)
	if len(pbhuo.hooks) == 0 {
		node, err = pbhuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductBrowseHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pbhuo.mutation = mutation
			node, err = pbhuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pbhuo.hooks) - 1; i >= 0; i-- {
			if pbhuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pbhuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pbhuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pbhuo *ProductBrowseHistoryUpdateOne) SaveX(ctx context.Context) *ProductBrowseHistory {
	node, err := pbhuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pbhuo *ProductBrowseHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := pbhuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pbhuo *ProductBrowseHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := pbhuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pbhuo *ProductBrowseHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ProductBrowseHistory, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productbrowsehistory.Table,
			Columns: productbrowsehistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productbrowsehistory.FieldID,
			},
		},
	}
	id, ok := pbhuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductBrowseHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pbhuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productbrowsehistory.FieldID)
		for _, f := range fields {
			if !productbrowsehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productbrowsehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pbhuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProductBrowseHistory{config: pbhuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pbhuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productbrowsehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
