// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productevaluation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductEvaluationDelete is the builder for deleting a ProductEvaluation entity.
type ProductEvaluationDelete struct {
	config
	hooks    []Hook
	mutation *ProductEvaluationMutation
}

// Where appends a list predicates to the ProductEvaluationDelete builder.
func (ped *ProductEvaluationDelete) Where(ps ...predicate.ProductEvaluation) *ProductEvaluationDelete {
	ped.mutation.Where(ps...)
	return ped
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ped *ProductEvaluationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ped.hooks) == 0 {
		affected, err = ped.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductEvaluationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ped.mutation = mutation
			affected, err = ped.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ped.hooks) - 1; i >= 0; i-- {
			if ped.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ped.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ped.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ped *ProductEvaluationDelete) ExecX(ctx context.Context) int {
	n, err := ped.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ped *ProductEvaluationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productevaluation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productevaluation.FieldID,
			},
		},
	}
	if ps := ped.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ped.driver, _spec)
}

// ProductEvaluationDeleteOne is the builder for deleting a single ProductEvaluation entity.
type ProductEvaluationDeleteOne struct {
	ped *ProductEvaluationDelete
}

// Exec executes the deletion query.
func (pedo *ProductEvaluationDeleteOne) Exec(ctx context.Context) error {
	n, err := pedo.ped.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productevaluation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pedo *ProductEvaluationDeleteOne) ExecX(ctx context.Context) {
	pedo.ped.ExecX(ctx)
}
