// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/productbrowsehistory"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// ProductBrowseHistory is the model entity for the ProductBrowseHistory schema.
type ProductBrowseHistory struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductBrowseHistory) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case productbrowsehistory.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ProductBrowseHistory", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductBrowseHistory fields.
func (pbh *ProductBrowseHistory) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productbrowsehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pbh.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ProductBrowseHistory.
// Note that you need to call ProductBrowseHistory.Unwrap() before calling this method if this ProductBrowseHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (pbh *ProductBrowseHistory) Update() *ProductBrowseHistoryUpdateOne {
	return (&ProductBrowseHistoryClient{config: pbh.config}).UpdateOne(pbh)
}

// Unwrap unwraps the ProductBrowseHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pbh *ProductBrowseHistory) Unwrap() *ProductBrowseHistory {
	tx, ok := pbh.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductBrowseHistory is not a transactional entity")
	}
	pbh.config.driver = tx.drv
	return pbh
}

// String implements the fmt.Stringer.
func (pbh *ProductBrowseHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ProductBrowseHistory(")
	builder.WriteString(fmt.Sprintf("id=%v", pbh.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ProductBrowseHistories is a parsable slice of ProductBrowseHistory.
type ProductBrowseHistories []*ProductBrowseHistory

func (pbh ProductBrowseHistories) config(cfg config) {
	for _i := range pbh {
		pbh[_i].config = cfg
	}
}
