// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productattributekey"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeKeyDelete is the builder for deleting a ProductAttributeKey entity.
type ProductAttributeKeyDelete struct {
	config
	hooks    []Hook
	mutation *ProductAttributeKeyMutation
}

// Where appends a list predicates to the ProductAttributeKeyDelete builder.
func (pakd *ProductAttributeKeyDelete) Where(ps ...predicate.ProductAttributeKey) *ProductAttributeKeyDelete {
	pakd.mutation.Where(ps...)
	return pakd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pakd *ProductAttributeKeyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pakd.hooks) == 0 {
		affected, err = pakd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttributeKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pakd.mutation = mutation
			affected, err = pakd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pakd.hooks) - 1; i >= 0; i-- {
			if pakd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pakd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pakd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pakd *ProductAttributeKeyDelete) ExecX(ctx context.Context) int {
	n, err := pakd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pakd *ProductAttributeKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productattributekey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributekey.FieldID,
			},
		},
	}
	if ps := pakd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pakd.driver, _spec)
}

// ProductAttributeKeyDeleteOne is the builder for deleting a single ProductAttributeKey entity.
type ProductAttributeKeyDeleteOne struct {
	pakd *ProductAttributeKeyDelete
}

// Exec executes the deletion query.
func (pakdo *ProductAttributeKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := pakdo.pakd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productattributekey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pakdo *ProductAttributeKeyDeleteOne) ExecX(ctx context.Context) {
	pakdo.pakd.ExecX(ctx)
}
