// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productevaluation"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductEvaluationQuery is the builder for querying ProductEvaluation entities.
type ProductEvaluationQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProductEvaluation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductEvaluationQuery builder.
func (peq *ProductEvaluationQuery) Where(ps ...predicate.ProductEvaluation) *ProductEvaluationQuery {
	peq.predicates = append(peq.predicates, ps...)
	return peq
}

// Limit adds a limit step to the query.
func (peq *ProductEvaluationQuery) Limit(limit int) *ProductEvaluationQuery {
	peq.limit = &limit
	return peq
}

// Offset adds an offset step to the query.
func (peq *ProductEvaluationQuery) Offset(offset int) *ProductEvaluationQuery {
	peq.offset = &offset
	return peq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (peq *ProductEvaluationQuery) Unique(unique bool) *ProductEvaluationQuery {
	peq.unique = &unique
	return peq
}

// Order adds an order step to the query.
func (peq *ProductEvaluationQuery) Order(o ...OrderFunc) *ProductEvaluationQuery {
	peq.order = append(peq.order, o...)
	return peq
}

// First returns the first ProductEvaluation entity from the query.
// Returns a *NotFoundError when no ProductEvaluation was found.
func (peq *ProductEvaluationQuery) First(ctx context.Context) (*ProductEvaluation, error) {
	nodes, err := peq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productevaluation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (peq *ProductEvaluationQuery) FirstX(ctx context.Context) *ProductEvaluation {
	node, err := peq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductEvaluation ID from the query.
// Returns a *NotFoundError when no ProductEvaluation ID was found.
func (peq *ProductEvaluationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productevaluation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (peq *ProductEvaluationQuery) FirstIDX(ctx context.Context) int {
	id, err := peq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductEvaluation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductEvaluation entity is found.
// Returns a *NotFoundError when no ProductEvaluation entities are found.
func (peq *ProductEvaluationQuery) Only(ctx context.Context) (*ProductEvaluation, error) {
	nodes, err := peq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productevaluation.Label}
	default:
		return nil, &NotSingularError{productevaluation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (peq *ProductEvaluationQuery) OnlyX(ctx context.Context) *ProductEvaluation {
	node, err := peq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductEvaluation ID in the query.
// Returns a *NotSingularError when more than one ProductEvaluation ID is found.
// Returns a *NotFoundError when no entities are found.
func (peq *ProductEvaluationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = &NotSingularError{productevaluation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (peq *ProductEvaluationQuery) OnlyIDX(ctx context.Context) int {
	id, err := peq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductEvaluations.
func (peq *ProductEvaluationQuery) All(ctx context.Context) ([]*ProductEvaluation, error) {
	if err := peq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return peq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (peq *ProductEvaluationQuery) AllX(ctx context.Context) []*ProductEvaluation {
	nodes, err := peq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductEvaluation IDs.
func (peq *ProductEvaluationQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := peq.Select(productevaluation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (peq *ProductEvaluationQuery) IDsX(ctx context.Context) []int {
	ids, err := peq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (peq *ProductEvaluationQuery) Count(ctx context.Context) (int, error) {
	if err := peq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return peq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (peq *ProductEvaluationQuery) CountX(ctx context.Context) int {
	count, err := peq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (peq *ProductEvaluationQuery) Exist(ctx context.Context) (bool, error) {
	if err := peq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return peq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (peq *ProductEvaluationQuery) ExistX(ctx context.Context) bool {
	exist, err := peq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductEvaluationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (peq *ProductEvaluationQuery) Clone() *ProductEvaluationQuery {
	if peq == nil {
		return nil
	}
	return &ProductEvaluationQuery{
		config:     peq.config,
		limit:      peq.limit,
		offset:     peq.offset,
		order:      append([]OrderFunc{}, peq.order...),
		predicates: append([]predicate.ProductEvaluation{}, peq.predicates...),
		// clone intermediate query.
		sql:    peq.sql.Clone(),
		path:   peq.path,
		unique: peq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (peq *ProductEvaluationQuery) GroupBy(field string, fields ...string) *ProductEvaluationGroupBy {
	group := &ProductEvaluationGroupBy{config: peq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := peq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return peq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (peq *ProductEvaluationQuery) Select(fields ...string) *ProductEvaluationSelect {
	peq.fields = append(peq.fields, fields...)
	return &ProductEvaluationSelect{ProductEvaluationQuery: peq}
}

func (peq *ProductEvaluationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range peq.fields {
		if !productevaluation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if peq.path != nil {
		prev, err := peq.path(ctx)
		if err != nil {
			return err
		}
		peq.sql = prev
	}
	return nil
}

func (peq *ProductEvaluationQuery) sqlAll(ctx context.Context) ([]*ProductEvaluation, error) {
	var (
		nodes = []*ProductEvaluation{}
		_spec = peq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProductEvaluation{config: peq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, peq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (peq *ProductEvaluationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := peq.querySpec()
	_spec.Node.Columns = peq.fields
	if len(peq.fields) > 0 {
		_spec.Unique = peq.unique != nil && *peq.unique
	}
	return sqlgraph.CountNodes(ctx, peq.driver, _spec)
}

func (peq *ProductEvaluationQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := peq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (peq *ProductEvaluationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productevaluation.Table,
			Columns: productevaluation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productevaluation.FieldID,
			},
		},
		From:   peq.sql,
		Unique: true,
	}
	if unique := peq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := peq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productevaluation.FieldID)
		for i := range fields {
			if fields[i] != productevaluation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := peq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := peq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := peq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := peq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (peq *ProductEvaluationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(peq.driver.Dialect())
	t1 := builder.Table(productevaluation.Table)
	columns := peq.fields
	if len(columns) == 0 {
		columns = productevaluation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if peq.sql != nil {
		selector = peq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if peq.unique != nil && *peq.unique {
		selector.Distinct()
	}
	for _, p := range peq.predicates {
		p(selector)
	}
	for _, p := range peq.order {
		p(selector)
	}
	if offset := peq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := peq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductEvaluationGroupBy is the group-by builder for ProductEvaluation entities.
type ProductEvaluationGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pegb *ProductEvaluationGroupBy) Aggregate(fns ...AggregateFunc) *ProductEvaluationGroupBy {
	pegb.fns = append(pegb.fns, fns...)
	return pegb
}

// Scan applies the group-by query and scans the result into the given value.
func (pegb *ProductEvaluationGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pegb.path(ctx)
	if err != nil {
		return err
	}
	pegb.sql = query
	return pegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pegb.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) StringsX(ctx context.Context) []string {
	v, err := pegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) StringX(ctx context.Context) string {
	v, err := pegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pegb.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) IntsX(ctx context.Context) []int {
	v, err := pegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) IntX(ctx context.Context) int {
	v, err := pegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pegb.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pegb.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pegb *ProductEvaluationGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pegb *ProductEvaluationGroupBy) BoolX(ctx context.Context) bool {
	v, err := pegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pegb *ProductEvaluationGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pegb.fields {
		if !productevaluation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pegb *ProductEvaluationGroupBy) sqlQuery() *sql.Selector {
	selector := pegb.sql.Select()
	aggregation := make([]string, 0, len(pegb.fns))
	for _, fn := range pegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pegb.fields)+len(pegb.fns))
		for _, f := range pegb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pegb.fields...)...)
}

// ProductEvaluationSelect is the builder for selecting fields of ProductEvaluation entities.
type ProductEvaluationSelect struct {
	*ProductEvaluationQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pes *ProductEvaluationSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pes.prepareQuery(ctx); err != nil {
		return err
	}
	pes.sql = pes.ProductEvaluationQuery.sqlQuery(ctx)
	return pes.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pes *ProductEvaluationSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pes.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pes.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pes *ProductEvaluationSelect) StringsX(ctx context.Context) []string {
	v, err := pes.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pes.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pes *ProductEvaluationSelect) StringX(ctx context.Context) string {
	v, err := pes.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pes.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pes *ProductEvaluationSelect) IntsX(ctx context.Context) []int {
	v, err := pes.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pes.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pes *ProductEvaluationSelect) IntX(ctx context.Context) int {
	v, err := pes.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pes.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pes *ProductEvaluationSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pes.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pes.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pes *ProductEvaluationSelect) Float64X(ctx context.Context) float64 {
	v, err := pes.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pes.fields) > 1 {
		return nil, errors.New("ent: ProductEvaluationSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pes *ProductEvaluationSelect) BoolsX(ctx context.Context) []bool {
	v, err := pes.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pes *ProductEvaluationSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pes.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productevaluation.Label}
	default:
		err = fmt.Errorf("ent: ProductEvaluationSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pes *ProductEvaluationSelect) BoolX(ctx context.Context) bool {
	v, err := pes.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pes *ProductEvaluationSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pes.sql.Query()
	if err := pes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
