// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productevaluation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductEvaluationUpdate is the builder for updating ProductEvaluation entities.
type ProductEvaluationUpdate struct {
	config
	hooks    []Hook
	mutation *ProductEvaluationMutation
}

// Where appends a list predicates to the ProductEvaluationUpdate builder.
func (peu *ProductEvaluationUpdate) Where(ps ...predicate.ProductEvaluation) *ProductEvaluationUpdate {
	peu.mutation.Where(ps...)
	return peu
}

// Mutation returns the ProductEvaluationMutation object of the builder.
func (peu *ProductEvaluationUpdate) Mutation() *ProductEvaluationMutation {
	return peu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (peu *ProductEvaluationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(peu.hooks) == 0 {
		affected, err = peu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductEvaluationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			peu.mutation = mutation
			affected, err = peu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(peu.hooks) - 1; i >= 0; i-- {
			if peu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = peu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, peu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (peu *ProductEvaluationUpdate) SaveX(ctx context.Context) int {
	affected, err := peu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (peu *ProductEvaluationUpdate) Exec(ctx context.Context) error {
	_, err := peu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (peu *ProductEvaluationUpdate) ExecX(ctx context.Context) {
	if err := peu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (peu *ProductEvaluationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productevaluation.Table,
			Columns: productevaluation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productevaluation.FieldID,
			},
		},
	}
	if ps := peu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, peu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productevaluation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ProductEvaluationUpdateOne is the builder for updating a single ProductEvaluation entity.
type ProductEvaluationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductEvaluationMutation
}

// Mutation returns the ProductEvaluationMutation object of the builder.
func (peuo *ProductEvaluationUpdateOne) Mutation() *ProductEvaluationMutation {
	return peuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (peuo *ProductEvaluationUpdateOne) Select(field string, fields ...string) *ProductEvaluationUpdateOne {
	peuo.fields = append([]string{field}, fields...)
	return peuo
}

// Save executes the query and returns the updated ProductEvaluation entity.
func (peuo *ProductEvaluationUpdateOne) Save(ctx context.Context) (*ProductEvaluation, error) {
	var (
		err  error
		node *ProductEvaluation
	)
	if len(peuo.hooks) == 0 {
		node, err = peuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductEvaluationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			peuo.mutation = mutation
			node, err = peuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(peuo.hooks) - 1; i >= 0; i-- {
			if peuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = peuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, peuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (peuo *ProductEvaluationUpdateOne) SaveX(ctx context.Context) *ProductEvaluation {
	node, err := peuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (peuo *ProductEvaluationUpdateOne) Exec(ctx context.Context) error {
	_, err := peuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (peuo *ProductEvaluationUpdateOne) ExecX(ctx context.Context) {
	if err := peuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (peuo *ProductEvaluationUpdateOne) sqlSave(ctx context.Context) (_node *ProductEvaluation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productevaluation.Table,
			Columns: productevaluation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productevaluation.FieldID,
			},
		},
	}
	id, ok := peuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductEvaluation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := peuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productevaluation.FieldID)
		for _, f := range fields {
			if !productevaluation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productevaluation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := peuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProductEvaluation{config: peuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, peuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productevaluation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
