// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productfocus"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductFocusUpdate is the builder for updating ProductFocus entities.
type ProductFocusUpdate struct {
	config
	hooks    []Hook
	mutation *ProductFocusMutation
}

// Where appends a list predicates to the ProductFocusUpdate builder.
func (pfu *ProductFocusUpdate) Where(ps ...predicate.ProductFocus) *ProductFocusUpdate {
	pfu.mutation.Where(ps...)
	return pfu
}

// Mutation returns the ProductFocusMutation object of the builder.
func (pfu *ProductFocusUpdate) Mutation() *ProductFocusMutation {
	return pfu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pfu *ProductFocusUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pfu.hooks) == 0 {
		affected, err = pfu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductFocusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pfu.mutation = mutation
			affected, err = pfu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pfu.hooks) - 1; i >= 0; i-- {
			if pfu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pfu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pfu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pfu *ProductFocusUpdate) SaveX(ctx context.Context) int {
	affected, err := pfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pfu *ProductFocusUpdate) Exec(ctx context.Context) error {
	_, err := pfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfu *ProductFocusUpdate) ExecX(ctx context.Context) {
	if err := pfu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pfu *ProductFocusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productfocus.Table,
			Columns: productfocus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productfocus.FieldID,
			},
		},
	}
	if ps := pfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productfocus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ProductFocusUpdateOne is the builder for updating a single ProductFocus entity.
type ProductFocusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductFocusMutation
}

// Mutation returns the ProductFocusMutation object of the builder.
func (pfuo *ProductFocusUpdateOne) Mutation() *ProductFocusMutation {
	return pfuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pfuo *ProductFocusUpdateOne) Select(field string, fields ...string) *ProductFocusUpdateOne {
	pfuo.fields = append([]string{field}, fields...)
	return pfuo
}

// Save executes the query and returns the updated ProductFocus entity.
func (pfuo *ProductFocusUpdateOne) Save(ctx context.Context) (*ProductFocus, error) {
	var (
		err  error
		node *ProductFocus
	)
	if len(pfuo.hooks) == 0 {
		node, err = pfuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductFocusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pfuo.mutation = mutation
			node, err = pfuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pfuo.hooks) - 1; i >= 0; i-- {
			if pfuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pfuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pfuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pfuo *ProductFocusUpdateOne) SaveX(ctx context.Context) *ProductFocus {
	node, err := pfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pfuo *ProductFocusUpdateOne) Exec(ctx context.Context) error {
	_, err := pfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pfuo *ProductFocusUpdateOne) ExecX(ctx context.Context) {
	if err := pfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pfuo *ProductFocusUpdateOne) sqlSave(ctx context.Context) (_node *ProductFocus, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productfocus.Table,
			Columns: productfocus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productfocus.FieldID,
			},
		},
	}
	id, ok := pfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductFocus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productfocus.FieldID)
		for _, f := range fields {
			if !productfocus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productfocus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProductFocus{config: pfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productfocus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
