// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/productspecs"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// ProductSpecs is the model entity for the ProductSpecs schema.
type ProductSpecs struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductSpecs) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case productspecs.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ProductSpecs", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductSpecs fields.
func (ps *ProductSpecs) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productspecs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ps.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ProductSpecs.
// Note that you need to call ProductSpecs.Unwrap() before calling this method if this ProductSpecs
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *ProductSpecs) Update() *ProductSpecsUpdateOne {
	return (&ProductSpecsClient{config: ps.config}).UpdateOne(ps)
}

// Unwrap unwraps the ProductSpecs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *ProductSpecs) Unwrap() *ProductSpecs {
	tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductSpecs is not a transactional entity")
	}
	ps.config.driver = tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *ProductSpecs) String() string {
	var builder strings.Builder
	builder.WriteString("ProductSpecs(")
	builder.WriteString(fmt.Sprintf("id=%v", ps.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ProductSpecsSlice is a parsable slice of ProductSpecs.
type ProductSpecsSlice []*ProductSpecs

func (ps ProductSpecsSlice) config(cfg config) {
	for _i := range ps {
		ps[_i].config = cfg
	}
}
