// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productattributevalue"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeValueDelete is the builder for deleting a ProductAttributeValue entity.
type ProductAttributeValueDelete struct {
	config
	hooks    []Hook
	mutation *ProductAttributeValueMutation
}

// Where appends a list predicates to the ProductAttributeValueDelete builder.
func (pavd *ProductAttributeValueDelete) Where(ps ...predicate.ProductAttributeValue) *ProductAttributeValueDelete {
	pavd.mutation.Where(ps...)
	return pavd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pavd *ProductAttributeValueDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pavd.hooks) == 0 {
		affected, err = pavd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttributeValueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pavd.mutation = mutation
			affected, err = pavd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pavd.hooks) - 1; i >= 0; i-- {
			if pavd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pavd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pavd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pavd *ProductAttributeValueDelete) ExecX(ctx context.Context) int {
	n, err := pavd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pavd *ProductAttributeValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productattributevalue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributevalue.FieldID,
			},
		},
	}
	if ps := pavd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pavd.driver, _spec)
}

// ProductAttributeValueDeleteOne is the builder for deleting a single ProductAttributeValue entity.
type ProductAttributeValueDeleteOne struct {
	pavd *ProductAttributeValueDelete
}

// Exec executes the deletion query.
func (pavdo *ProductAttributeValueDeleteOne) Exec(ctx context.Context) error {
	n, err := pavdo.pavd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productattributevalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pavdo *ProductAttributeValueDeleteOne) ExecX(ctx context.Context) {
	pavdo.pavd.ExecX(ctx)
}
