// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ice-mall/ent/productattributekey"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeKeyCreate is the builder for creating a ProductAttributeKey entity.
type ProductAttributeKeyCreate struct {
	config
	mutation *ProductAttributeKeyMutation
	hooks    []Hook
}

// Mutation returns the ProductAttributeKeyMutation object of the builder.
func (pakc *ProductAttributeKeyCreate) Mutation() *ProductAttributeKeyMutation {
	return pakc.mutation
}

// Save creates the ProductAttributeKey in the database.
func (pakc *ProductAttributeKeyCreate) Save(ctx context.Context) (*ProductAttributeKey, error) {
	var (
		err  error
		node *ProductAttributeKey
	)
	if len(pakc.hooks) == 0 {
		if err = pakc.check(); err != nil {
			return nil, err
		}
		node, err = pakc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttributeKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pakc.check(); err != nil {
				return nil, err
			}
			pakc.mutation = mutation
			if node, err = pakc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pakc.hooks) - 1; i >= 0; i-- {
			if pakc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pakc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pakc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pakc *ProductAttributeKeyCreate) SaveX(ctx context.Context) *ProductAttributeKey {
	v, err := pakc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pakc *ProductAttributeKeyCreate) Exec(ctx context.Context) error {
	_, err := pakc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pakc *ProductAttributeKeyCreate) ExecX(ctx context.Context) {
	if err := pakc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pakc *ProductAttributeKeyCreate) check() error {
	return nil
}

func (pakc *ProductAttributeKeyCreate) sqlSave(ctx context.Context) (*ProductAttributeKey, error) {
	_node, _spec := pakc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pakc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pakc *ProductAttributeKeyCreate) createSpec() (*ProductAttributeKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductAttributeKey{config: pakc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productattributekey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributekey.FieldID,
			},
		}
	)
	return _node, _spec
}

// ProductAttributeKeyCreateBulk is the builder for creating many ProductAttributeKey entities in bulk.
type ProductAttributeKeyCreateBulk struct {
	config
	builders []*ProductAttributeKeyCreate
}

// Save creates the ProductAttributeKey entities in the database.
func (pakcb *ProductAttributeKeyCreateBulk) Save(ctx context.Context) ([]*ProductAttributeKey, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pakcb.builders))
	nodes := make([]*ProductAttributeKey, len(pakcb.builders))
	mutators := make([]Mutator, len(pakcb.builders))
	for i := range pakcb.builders {
		func(i int, root context.Context) {
			builder := pakcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductAttributeKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pakcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pakcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pakcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pakcb *ProductAttributeKeyCreateBulk) SaveX(ctx context.Context) []*ProductAttributeKey {
	v, err := pakcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pakcb *ProductAttributeKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := pakcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pakcb *ProductAttributeKeyCreateBulk) ExecX(ctx context.Context) {
	if err := pakcb.Exec(ctx); err != nil {
		panic(err)
	}
}
