// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/productattributekey"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeKeyQuery is the builder for querying ProductAttributeKey entities.
type ProductAttributeKeyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProductAttributeKey
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductAttributeKeyQuery builder.
func (pakq *ProductAttributeKeyQuery) Where(ps ...predicate.ProductAttributeKey) *ProductAttributeKeyQuery {
	pakq.predicates = append(pakq.predicates, ps...)
	return pakq
}

// Limit adds a limit step to the query.
func (pakq *ProductAttributeKeyQuery) Limit(limit int) *ProductAttributeKeyQuery {
	pakq.limit = &limit
	return pakq
}

// Offset adds an offset step to the query.
func (pakq *ProductAttributeKeyQuery) Offset(offset int) *ProductAttributeKeyQuery {
	pakq.offset = &offset
	return pakq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pakq *ProductAttributeKeyQuery) Unique(unique bool) *ProductAttributeKeyQuery {
	pakq.unique = &unique
	return pakq
}

// Order adds an order step to the query.
func (pakq *ProductAttributeKeyQuery) Order(o ...OrderFunc) *ProductAttributeKeyQuery {
	pakq.order = append(pakq.order, o...)
	return pakq
}

// First returns the first ProductAttributeKey entity from the query.
// Returns a *NotFoundError when no ProductAttributeKey was found.
func (pakq *ProductAttributeKeyQuery) First(ctx context.Context) (*ProductAttributeKey, error) {
	nodes, err := pakq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productattributekey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) FirstX(ctx context.Context) *ProductAttributeKey {
	node, err := pakq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductAttributeKey ID from the query.
// Returns a *NotFoundError when no ProductAttributeKey ID was found.
func (pakq *ProductAttributeKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pakq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productattributekey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := pakq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductAttributeKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductAttributeKey entity is found.
// Returns a *NotFoundError when no ProductAttributeKey entities are found.
func (pakq *ProductAttributeKeyQuery) Only(ctx context.Context) (*ProductAttributeKey, error) {
	nodes, err := pakq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productattributekey.Label}
	default:
		return nil, &NotSingularError{productattributekey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) OnlyX(ctx context.Context) *ProductAttributeKey {
	node, err := pakq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductAttributeKey ID in the query.
// Returns a *NotSingularError when more than one ProductAttributeKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (pakq *ProductAttributeKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pakq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = &NotSingularError{productattributekey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := pakq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductAttributeKeys.
func (pakq *ProductAttributeKeyQuery) All(ctx context.Context) ([]*ProductAttributeKey, error) {
	if err := pakq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pakq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) AllX(ctx context.Context) []*ProductAttributeKey {
	nodes, err := pakq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductAttributeKey IDs.
func (pakq *ProductAttributeKeyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pakq.Select(productattributekey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := pakq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pakq *ProductAttributeKeyQuery) Count(ctx context.Context) (int, error) {
	if err := pakq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pakq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) CountX(ctx context.Context) int {
	count, err := pakq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pakq *ProductAttributeKeyQuery) Exist(ctx context.Context) (bool, error) {
	if err := pakq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pakq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pakq *ProductAttributeKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := pakq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductAttributeKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pakq *ProductAttributeKeyQuery) Clone() *ProductAttributeKeyQuery {
	if pakq == nil {
		return nil
	}
	return &ProductAttributeKeyQuery{
		config:     pakq.config,
		limit:      pakq.limit,
		offset:     pakq.offset,
		order:      append([]OrderFunc{}, pakq.order...),
		predicates: append([]predicate.ProductAttributeKey{}, pakq.predicates...),
		// clone intermediate query.
		sql:    pakq.sql.Clone(),
		path:   pakq.path,
		unique: pakq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pakq *ProductAttributeKeyQuery) GroupBy(field string, fields ...string) *ProductAttributeKeyGroupBy {
	group := &ProductAttributeKeyGroupBy{config: pakq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pakq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pakq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pakq *ProductAttributeKeyQuery) Select(fields ...string) *ProductAttributeKeySelect {
	pakq.fields = append(pakq.fields, fields...)
	return &ProductAttributeKeySelect{ProductAttributeKeyQuery: pakq}
}

func (pakq *ProductAttributeKeyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pakq.fields {
		if !productattributekey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pakq.path != nil {
		prev, err := pakq.path(ctx)
		if err != nil {
			return err
		}
		pakq.sql = prev
	}
	return nil
}

func (pakq *ProductAttributeKeyQuery) sqlAll(ctx context.Context) ([]*ProductAttributeKey, error) {
	var (
		nodes = []*ProductAttributeKey{}
		_spec = pakq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProductAttributeKey{config: pakq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pakq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pakq *ProductAttributeKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pakq.querySpec()
	_spec.Node.Columns = pakq.fields
	if len(pakq.fields) > 0 {
		_spec.Unique = pakq.unique != nil && *pakq.unique
	}
	return sqlgraph.CountNodes(ctx, pakq.driver, _spec)
}

func (pakq *ProductAttributeKeyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pakq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pakq *ProductAttributeKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productattributekey.Table,
			Columns: productattributekey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributekey.FieldID,
			},
		},
		From:   pakq.sql,
		Unique: true,
	}
	if unique := pakq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pakq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productattributekey.FieldID)
		for i := range fields {
			if fields[i] != productattributekey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pakq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pakq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pakq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pakq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pakq *ProductAttributeKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pakq.driver.Dialect())
	t1 := builder.Table(productattributekey.Table)
	columns := pakq.fields
	if len(columns) == 0 {
		columns = productattributekey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pakq.sql != nil {
		selector = pakq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pakq.unique != nil && *pakq.unique {
		selector.Distinct()
	}
	for _, p := range pakq.predicates {
		p(selector)
	}
	for _, p := range pakq.order {
		p(selector)
	}
	if offset := pakq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pakq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductAttributeKeyGroupBy is the group-by builder for ProductAttributeKey entities.
type ProductAttributeKeyGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pakgb *ProductAttributeKeyGroupBy) Aggregate(fns ...AggregateFunc) *ProductAttributeKeyGroupBy {
	pakgb.fns = append(pakgb.fns, fns...)
	return pakgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pakgb *ProductAttributeKeyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pakgb.path(ctx)
	if err != nil {
		return err
	}
	pakgb.sql = query
	return pakgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pakgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pakgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeyGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pakgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) StringsX(ctx context.Context) []string {
	v, err := pakgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pakgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeyGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) StringX(ctx context.Context) string {
	v, err := pakgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pakgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeyGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pakgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) IntsX(ctx context.Context) []int {
	v, err := pakgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pakgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeyGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) IntX(ctx context.Context) int {
	v, err := pakgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pakgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeyGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pakgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pakgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pakgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeyGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pakgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pakgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeyGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pakgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pakgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pakgb *ProductAttributeKeyGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pakgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeyGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pakgb *ProductAttributeKeyGroupBy) BoolX(ctx context.Context) bool {
	v, err := pakgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pakgb *ProductAttributeKeyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pakgb.fields {
		if !productattributekey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pakgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pakgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pakgb *ProductAttributeKeyGroupBy) sqlQuery() *sql.Selector {
	selector := pakgb.sql.Select()
	aggregation := make([]string, 0, len(pakgb.fns))
	for _, fn := range pakgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pakgb.fields)+len(pakgb.fns))
		for _, f := range pakgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pakgb.fields...)...)
}

// ProductAttributeKeySelect is the builder for selecting fields of ProductAttributeKey entities.
type ProductAttributeKeySelect struct {
	*ProductAttributeKeyQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (paks *ProductAttributeKeySelect) Scan(ctx context.Context, v interface{}) error {
	if err := paks.prepareQuery(ctx); err != nil {
		return err
	}
	paks.sql = paks.ProductAttributeKeyQuery.sqlQuery(ctx)
	return paks.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) ScanX(ctx context.Context, v interface{}) {
	if err := paks.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Strings(ctx context.Context) ([]string, error) {
	if len(paks.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := paks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) StringsX(ctx context.Context) []string {
	v, err := paks.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = paks.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) StringX(ctx context.Context) string {
	v, err := paks.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Ints(ctx context.Context) ([]int, error) {
	if len(paks.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := paks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) IntsX(ctx context.Context) []int {
	v, err := paks.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = paks.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) IntX(ctx context.Context) int {
	v, err := paks.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(paks.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := paks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) Float64sX(ctx context.Context) []float64 {
	v, err := paks.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = paks.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) Float64X(ctx context.Context) float64 {
	v, err := paks.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(paks.fields) > 1 {
		return nil, errors.New("ent: ProductAttributeKeySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := paks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) BoolsX(ctx context.Context) []bool {
	v, err := paks.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (paks *ProductAttributeKeySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = paks.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattributekey.Label}
	default:
		err = fmt.Errorf("ent: ProductAttributeKeySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (paks *ProductAttributeKeySelect) BoolX(ctx context.Context) bool {
	v, err := paks.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (paks *ProductAttributeKeySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := paks.sql.Query()
	if err := paks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
