// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ice-mall/ent/predicate"
	"ice-mall/ent/receivingaddress"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReceivingAddressQuery is the builder for querying ReceivingAddress entities.
type ReceivingAddressQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ReceivingAddress
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReceivingAddressQuery builder.
func (raq *ReceivingAddressQuery) Where(ps ...predicate.ReceivingAddress) *ReceivingAddressQuery {
	raq.predicates = append(raq.predicates, ps...)
	return raq
}

// Limit adds a limit step to the query.
func (raq *ReceivingAddressQuery) Limit(limit int) *ReceivingAddressQuery {
	raq.limit = &limit
	return raq
}

// Offset adds an offset step to the query.
func (raq *ReceivingAddressQuery) Offset(offset int) *ReceivingAddressQuery {
	raq.offset = &offset
	return raq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (raq *ReceivingAddressQuery) Unique(unique bool) *ReceivingAddressQuery {
	raq.unique = &unique
	return raq
}

// Order adds an order step to the query.
func (raq *ReceivingAddressQuery) Order(o ...OrderFunc) *ReceivingAddressQuery {
	raq.order = append(raq.order, o...)
	return raq
}

// First returns the first ReceivingAddress entity from the query.
// Returns a *NotFoundError when no ReceivingAddress was found.
func (raq *ReceivingAddressQuery) First(ctx context.Context) (*ReceivingAddress, error) {
	nodes, err := raq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{receivingaddress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (raq *ReceivingAddressQuery) FirstX(ctx context.Context) *ReceivingAddress {
	node, err := raq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReceivingAddress ID from the query.
// Returns a *NotFoundError when no ReceivingAddress ID was found.
func (raq *ReceivingAddressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = raq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{receivingaddress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (raq *ReceivingAddressQuery) FirstIDX(ctx context.Context) int {
	id, err := raq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReceivingAddress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReceivingAddress entity is found.
// Returns a *NotFoundError when no ReceivingAddress entities are found.
func (raq *ReceivingAddressQuery) Only(ctx context.Context) (*ReceivingAddress, error) {
	nodes, err := raq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{receivingaddress.Label}
	default:
		return nil, &NotSingularError{receivingaddress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (raq *ReceivingAddressQuery) OnlyX(ctx context.Context) *ReceivingAddress {
	node, err := raq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReceivingAddress ID in the query.
// Returns a *NotSingularError when more than one ReceivingAddress ID is found.
// Returns a *NotFoundError when no entities are found.
func (raq *ReceivingAddressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = raq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = &NotSingularError{receivingaddress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (raq *ReceivingAddressQuery) OnlyIDX(ctx context.Context) int {
	id, err := raq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReceivingAddresses.
func (raq *ReceivingAddressQuery) All(ctx context.Context) ([]*ReceivingAddress, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return raq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (raq *ReceivingAddressQuery) AllX(ctx context.Context) []*ReceivingAddress {
	nodes, err := raq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReceivingAddress IDs.
func (raq *ReceivingAddressQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := raq.Select(receivingaddress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (raq *ReceivingAddressQuery) IDsX(ctx context.Context) []int {
	ids, err := raq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (raq *ReceivingAddressQuery) Count(ctx context.Context) (int, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return raq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (raq *ReceivingAddressQuery) CountX(ctx context.Context) int {
	count, err := raq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (raq *ReceivingAddressQuery) Exist(ctx context.Context) (bool, error) {
	if err := raq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return raq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (raq *ReceivingAddressQuery) ExistX(ctx context.Context) bool {
	exist, err := raq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReceivingAddressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (raq *ReceivingAddressQuery) Clone() *ReceivingAddressQuery {
	if raq == nil {
		return nil
	}
	return &ReceivingAddressQuery{
		config:     raq.config,
		limit:      raq.limit,
		offset:     raq.offset,
		order:      append([]OrderFunc{}, raq.order...),
		predicates: append([]predicate.ReceivingAddress{}, raq.predicates...),
		// clone intermediate query.
		sql:    raq.sql.Clone(),
		path:   raq.path,
		unique: raq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (raq *ReceivingAddressQuery) GroupBy(field string, fields ...string) *ReceivingAddressGroupBy {
	group := &ReceivingAddressGroupBy{config: raq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := raq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return raq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (raq *ReceivingAddressQuery) Select(fields ...string) *ReceivingAddressSelect {
	raq.fields = append(raq.fields, fields...)
	return &ReceivingAddressSelect{ReceivingAddressQuery: raq}
}

func (raq *ReceivingAddressQuery) prepareQuery(ctx context.Context) error {
	for _, f := range raq.fields {
		if !receivingaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if raq.path != nil {
		prev, err := raq.path(ctx)
		if err != nil {
			return err
		}
		raq.sql = prev
	}
	return nil
}

func (raq *ReceivingAddressQuery) sqlAll(ctx context.Context) ([]*ReceivingAddress, error) {
	var (
		nodes = []*ReceivingAddress{}
		_spec = raq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ReceivingAddress{config: raq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, raq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (raq *ReceivingAddressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := raq.querySpec()
	_spec.Node.Columns = raq.fields
	if len(raq.fields) > 0 {
		_spec.Unique = raq.unique != nil && *raq.unique
	}
	return sqlgraph.CountNodes(ctx, raq.driver, _spec)
}

func (raq *ReceivingAddressQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := raq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (raq *ReceivingAddressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   receivingaddress.Table,
			Columns: receivingaddress.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: receivingaddress.FieldID,
			},
		},
		From:   raq.sql,
		Unique: true,
	}
	if unique := raq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := raq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, receivingaddress.FieldID)
		for i := range fields {
			if fields[i] != receivingaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := raq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := raq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := raq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := raq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (raq *ReceivingAddressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(raq.driver.Dialect())
	t1 := builder.Table(receivingaddress.Table)
	columns := raq.fields
	if len(columns) == 0 {
		columns = receivingaddress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if raq.sql != nil {
		selector = raq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if raq.unique != nil && *raq.unique {
		selector.Distinct()
	}
	for _, p := range raq.predicates {
		p(selector)
	}
	for _, p := range raq.order {
		p(selector)
	}
	if offset := raq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := raq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReceivingAddressGroupBy is the group-by builder for ReceivingAddress entities.
type ReceivingAddressGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ragb *ReceivingAddressGroupBy) Aggregate(fns ...AggregateFunc) *ReceivingAddressGroupBy {
	ragb.fns = append(ragb.fns, fns...)
	return ragb
}

// Scan applies the group-by query and scans the result into the given value.
func (ragb *ReceivingAddressGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ragb.path(ctx)
	if err != nil {
		return err
	}
	ragb.sql = query
	return ragb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ragb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ragb.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ragb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) StringsX(ctx context.Context) []string {
	v, err := ragb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ragb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) StringX(ctx context.Context) string {
	v, err := ragb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ragb.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ragb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) IntsX(ctx context.Context) []int {
	v, err := ragb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ragb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) IntX(ctx context.Context) int {
	v, err := ragb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ragb.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ragb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ragb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ragb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ragb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ragb.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ragb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ragb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ragb *ReceivingAddressGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ragb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ragb *ReceivingAddressGroupBy) BoolX(ctx context.Context) bool {
	v, err := ragb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ragb *ReceivingAddressGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ragb.fields {
		if !receivingaddress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ragb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ragb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ragb *ReceivingAddressGroupBy) sqlQuery() *sql.Selector {
	selector := ragb.sql.Select()
	aggregation := make([]string, 0, len(ragb.fns))
	for _, fn := range ragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ragb.fields)+len(ragb.fns))
		for _, f := range ragb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ragb.fields...)...)
}

// ReceivingAddressSelect is the builder for selecting fields of ReceivingAddress entities.
type ReceivingAddressSelect struct {
	*ReceivingAddressQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ras *ReceivingAddressSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ras.prepareQuery(ctx); err != nil {
		return err
	}
	ras.sql = ras.ReceivingAddressQuery.sqlQuery(ctx)
	return ras.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ras *ReceivingAddressSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ras.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ras.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ras.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ras *ReceivingAddressSelect) StringsX(ctx context.Context) []string {
	v, err := ras.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ras.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ras *ReceivingAddressSelect) StringX(ctx context.Context) string {
	v, err := ras.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ras.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ras.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ras *ReceivingAddressSelect) IntsX(ctx context.Context) []int {
	v, err := ras.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ras.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ras *ReceivingAddressSelect) IntX(ctx context.Context) int {
	v, err := ras.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ras.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ras.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ras *ReceivingAddressSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ras.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ras.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ras *ReceivingAddressSelect) Float64X(ctx context.Context) float64 {
	v, err := ras.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ras.fields) > 1 {
		return nil, errors.New("ent: ReceivingAddressSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ras.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ras *ReceivingAddressSelect) BoolsX(ctx context.Context) []bool {
	v, err := ras.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ras *ReceivingAddressSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ras.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{receivingaddress.Label}
	default:
		err = fmt.Errorf("ent: ReceivingAddressSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ras *ReceivingAddressSelect) BoolX(ctx context.Context) bool {
	v, err := ras.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ras *ReceivingAddressSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ras.sql.Query()
	if err := ras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
