// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"ice-mall/ent/userintegral"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// UserIntegral is the model entity for the UserIntegral schema.
type UserIntegral struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserIntegral) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case userintegral.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserIntegral", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserIntegral fields.
func (ui *UserIntegral) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userintegral.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ui.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this UserIntegral.
// Note that you need to call UserIntegral.Unwrap() before calling this method if this UserIntegral
// was returned from a transaction, and the transaction was committed or rolled back.
func (ui *UserIntegral) Update() *UserIntegralUpdateOne {
	return (&UserIntegralClient{config: ui.config}).UpdateOne(ui)
}

// Unwrap unwraps the UserIntegral entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ui *UserIntegral) Unwrap() *UserIntegral {
	tx, ok := ui.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserIntegral is not a transactional entity")
	}
	ui.config.driver = tx.drv
	return ui
}

// String implements the fmt.Stringer.
func (ui *UserIntegral) String() string {
	var builder strings.Builder
	builder.WriteString("UserIntegral(")
	builder.WriteString(fmt.Sprintf("id=%v", ui.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserIntegrals is a parsable slice of UserIntegral.
type UserIntegrals []*UserIntegral

func (ui UserIntegrals) config(cfg config) {
	for _i := range ui {
		ui[_i].config = cfg
	}
}
