// Code generated by entc, DO NOT EDIT.

package datadictionarykey

const (
	// Label holds the string label denoting the datadictionarykey type in the database.
	Label = "data_dictionary_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the datadictionarykey in the database.
	Table = "data_dictionary_keys"
)

// Columns holds all SQL columns for datadictionarykey fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
