// Code generated by entc, DO NOT EDIT.

package productfocus

const (
	// Label holds the string label denoting the productfocus type in the database.
	Label = "product_focus"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the productfocus in the database.
	Table = "product_focus"
)

// Columns holds all SQL columns for productfocus fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
