// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Captcha is the predicate function for captcha builders.
type Captcha func(*sql.Selector)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
